name: CSync
version: 1.0
main: org.charlie.cSync.CSync
api-version: 1.20
commands:
  verify:
    description: Verifies the given code.
    usage: /verify <code>
    permission: cSync.use
  csync:
    description: Reloads the CSync plugin or set the world.
    permission: cSync.reload
